# Generated by Django 6.0.7 on 2026-07-16 16:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('is_default', models.BooleanField(default=False)),
                ('options', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='downloads.folder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(default='#8b5cf6', max_length=7)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('url', models.URLField(max_length=2048)),
                ('platform', models.CharField(blank=True, db_index=True, max_length=64)),
                ('platform_display', models.CharField(blank=True, max_length=64)),
                ('extractor', models.CharField(blank=True, max_length=64)),
                ('video_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('description', models.TextField(blank=True)),
                ('uploader', models.CharField(blank=True, max_length=256)),
                ('uploader_id', models.CharField(blank=True, max_length=128)),
                ('thumbnail_url', models.URLField(blank=True, max_length=2048)),
                ('thumbnail_local', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('view_count', models.BigIntegerField(blank=True, null=True)),
                ('like_count', models.BigIntegerField(blank=True, null=True)),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('webpage_url', models.URLField(blank=True, max_length=2048)),
                ('is_live', models.BooleanField(default=False)),
                ('is_playlist', models.BooleanField(default=False)),
                ('playlist_count', models.PositiveIntegerField(blank=True, null=True)),
                ('playlist_index', models.PositiveIntegerField(blank=True, null=True)),
                ('chapters', models.JSONField(blank=True, default=list)),
                ('subtitles_available', models.JSONField(blank=True, default=list)),
                ('formats_available', models.JSONField(blank=True, default=list)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('mode', models.CharField(choices=[('video_audio', 'Video + Audio'), ('video_only', 'Video Only'), ('audio_only', 'Audio Only'), ('subtitles', 'Subtitles'), ('thumbnail', 'Thumbnail'), ('metadata', 'Metadata'), ('playlist', 'Playlist'), ('channel', 'Channel')], default='video_audio', max_length=32)),
                ('quality', models.CharField(default='best', max_length=32)),
                ('audio_quality', models.CharField(default='192', max_length=32)),
                ('output_format', models.CharField(default='mp4', max_length=16)),
                ('audio_format', models.CharField(default='mp3', max_length=16)),
                ('selected_format_id', models.CharField(blank=True, max_length=64)),
                ('subtitle_langs', models.JSONField(blank=True, default=list)),
                ('embed_subs', models.BooleanField(default=False)),
                ('embed_thumbnail', models.BooleanField(default=True)),
                ('embed_metadata', models.BooleanField(default=True)),
                ('write_description', models.BooleanField(default=False)),
                ('write_thumbnail', models.BooleanField(default=False)),
                ('playlist_start', models.PositiveIntegerField(blank=True, null=True)),
                ('playlist_end', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_filename', models.CharField(blank=True, max_length=512)),
                ('bandwidth_limit_kbps', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetching_meta', 'Fetching Metadata'), ('queued', 'Queued'), ('downloading', 'Downloading'), ('processing', 'Processing'), ('merging', 'Merging'), ('converting', 'Converting'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=32)),
                ('stage', models.CharField(blank=True, max_length=64)),
                ('progress', models.FloatField(default=0.0)),
                ('speed_bps', models.FloatField(blank=True, null=True)),
                ('eta_seconds', models.IntegerField(blank=True, null=True)),
                ('downloaded_bytes', models.BigIntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(blank=True, null=True)),
                ('queue_position', models.PositiveIntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(choices=[(0, 'Low'), (5, 'Normal'), (10, 'High'), (20, 'Urgent')], default=5)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=1024)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('resolution', models.CharField(blank=True, max_length=32)),
                ('vcodec', models.CharField(blank=True, max_length=64)),
                ('acodec', models.CharField(blank=True, max_length=64)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('audio_bitrate', models.PositiveIntegerField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to='downloads.folder')),
                ('tags', models.ManyToManyField(blank=True, related_name='downloads', to='downloads.tag')),
            ],
            options={
                'verbose_name': 'Download Job',
                'verbose_name_plural': 'Download Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateFingerprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=64)),
                ('video_id', models.CharField(max_length=128)),
                ('quality', models.CharField(blank=True, max_length=32)),
                ('mode', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='downloads.downloadjob')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_fingerprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'platform', 'video_id'], name='downloads_d_user_id_0f8a99_idx')],
                'unique_together': {('user', 'platform', 'video_id', 'quality', 'mode')},
            },
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(fields=['user', 'status', '-created_at'], name='downloads_d_user_id_50e969_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(fields=['session_key', 'status'], name='downloads_d_session_9e0976_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(fields=['platform', '-created_at'], name='downloads_d_platfor_835b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='downloads_d_status_f381f4_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(fields=['is_deleted', '-created_at'], name='downloads_d_is_dele_21ca9c_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(fields=['video_id', 'platform'], name='downloads_d_video_i_3b706c_idx'),
        ),
    ]
