# Generated by Django 6.0.7 on 2026-07-16 16:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('downloads_started', models.PositiveIntegerField(default=0)),
                ('downloads_completed', models.PositiveIntegerField(default=0)),
                ('downloads_failed', models.PositiveIntegerField(default=0)),
                ('bytes_downloaded', models.BigIntegerField(default=0)),
                ('avg_speed_bps', models.FloatField(blank=True, null=True)),
                ('platform_breakdown', models.JSONField(blank=True, default=dict)),
                ('format_breakdown', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, help_text='Null = global aggregate', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily stats',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
